server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  output:
    ansi:
      enabled: detect

debug: true
logging:
  file: d:/logs/SpringBoot-Learning.log
  level:
    com:
      example:
        demo: debug
    root: warn






